version: '3.8'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "droidTopic:1:1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  bishop:
    build: ./bishop-prototype
    environment:
      DEBUG: "true"
      DEBUG_PORT: 8001
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8001:8001"  # порт для отладки
      - "8081:8081"  # порт для отладки
    depends_on:
      - kafka
